name: Release assets

on:
  release:
    types:
      published

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      IS_VALID_TAG: ${{ steps.check.outputs.IS_VALID_TAG }}
    steps:
      - name: check tag version
        id: check
        run: |
          REF=${{ github.ref }}
          if [[ "$REF" =~ refs/tags/latest-[0-9]+.[0-9]+.[0-9]+ ]]; then
            IS_VALID_TAG=true
          elif [[ "$REF" =~ refs/tags/v[0-9]+.[0-9]+.[0-9]+ ]]; then
            IS_VALID_TAG=true
          else
              echo "Expected refs of the form 'refs/tags/[v,latest-]<major-version>.<minor-version>.<patch-version>' but got '$REF'"
              IS_VALID_TAG=false
          fi
          echo "IS_VALID_TAG=$IS_VALID_TAG"
          echo "IS_VALID_TAG=$IS_VALID_TAG" >> "$GITHUB_OUTPUT"
  build-and-upload:
    runs-on: ubuntu-latest
    needs: prepare
    if: needs.prepare.outputs.IS_VALID_TAG
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn clean package -DskipTests
      - uses: AButler/upload-release-assets@v2.0.2
        with:
          files: 'build/build-bifromq-starters/target/bifromq-*'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
